### ISSUE TITLE
Array patterns / nested patterns examples?

### ISSUE THREAD

**Issue by Ptival** [FGRibreau/match-when#16]
The documentation mentions:

```
[pattern0, ..., patternn] - matches any object with property names 0 to n matching patterns pattern0 to patternn, respectively.
```

Yet there are no examples. I have tried, and managed to make this work:

```
match([1, 2], { [when([1, 2])]: "it works" })
```

But I cannot understand a way to nest patterns the way the doc suggests:

```
match([when(), 2], { [when([1, 2])]: "it works" })
```

:(

**Comment by FGRibreau** [comment]
Wildcards are currently not supported but I welcome a PR for it :)

**Comment by FGRibreau** [comment]
Closed as https://github.com/FGRibreau/match-when/issues/14 already exists
