### ISSUE TITLE
when() is confusing. Consider always().

### ISSUE THREAD

**Issue by StevenACoffman** [FGRibreau/match-when#8]
Functional libraries generally use [always()](http://ramdajs.com/0.19.0/docs/#always) for a catch all function. It would allow you to simplify your `when` function a bit as well. By the way, thanks for a nice library!

**Comment by FGRibreau** [comment]
In fact when() is more like "_" in scala:

``` scala
    def describe(x: Any) = x match {
      case 5 => "five"
      case true => "truth"
      case "hello" => "hi!"
      case Nil => "the empty list"
      case _ => "something else"
    }
```

well, we could always set an alias of "when()" and require it with:

``` js
const {match, when,  _} = require('match-when');
```

or

``` js
const {match, when,  _:always} = require('match-when');
```

but it's harder to remember, if you want you can always set an alias for it:

``` js
const {match, when} = require('match-when');
const always = when;
```

So yeah, it's not planned and please note that the [mandatory catch-all will be removed in the next major](https://github.com/FGRibreau/match-when/issues/10) and will be replaced by a wildcard implementation :)
