### ISSUE TITLE
Consider avoiding conditionals

### ISSUE THREAD

**Issue by StevenACoffman** [FGRibreau/match-when#9]
I really like this library, but I find it a bit ironic that it is implemented using the conditionals it helps to avoid.

 Using arrays of patterns with actions with `Array.find` could simplify the code. [Here's an example](http://exercism.io/submissions/58c20904264e4f09b60d887cc677a37d) (please excuse the unsupported destructuring that's not needed).  The technique would simplify the if...return if...return...if...return portions of the code, and allow functions to have only one exit point. This would also reduce the cyclomatic complexity as well. I can do this, but I wanted to check if there was interest first.

**Comment by FGRibreau** [comment]
Definitely, I merged your PR, great work!
